### ISSUE TITLE
When fullscreen button clicked, it cause black background

### ISSUE THREAD

**Issue by consciousnessdev** [vasilevich/react-fullscreen-crossbrowser#3]
when i clicked fullscreen background it changes page background to black

![img](https://i.ibb.co/2yPR5Jr/image.png)

**Comment by vasilevich** [comment]
can you please show the way you use the fullscreen element,  eg a piece of code where you use it so that we can get an idea where something might of went wrong?

**Comment by vasilevich** [comment]
since you seem to be not responsive, I assume you got your issues resolved, I will close it and please feel free to open it if the question is still relevant.

**Comment by MichalPP** [comment]
for me, it's also with black background when fullscreen, [like here](https://www.iz.sk/sk/o-nas/aktualizovane#app). (click on F)
