### ISSUE TITLE
Upgrade to be compatible with React 16.x/17.x

### ISSUE THREAD

**Issue by hiradyazdan** [vasilevich/react-fullscreen-crossbrowser#4]
Is there any plan to upgrade this package so that it matches implementations for latest react 16.x and also be compatible with react 17.x later? I am referring to `UNSAFE_` prefix warnings for some of the lifecycle methods.

**Comment by Hmve** [comment]
I created a pullrequest which should fix this issue.

**Comment by vasilevich** [comment]
I accepted the pull and published to NPM, 
feel free to reopen the issue if you feel your needs have not been met.
