### ISSUE TITLE
react-fullscreen-crossbrowser is not scrollable

### ISSUE THREAD

**Issue by Vasanth-Korada** [vasilevich/react-fullscreen-crossbrowser#5]
I am using react-fullscreen-crossbrowser package. Full screen is working fine but I am unable to scroll under full screen mode. Could you please help me. Thanks!

		<Fullscreen
			enabled={isFullscreenEnabled}
			onChange={(isFullscreenEnabled) => setisFullscreenEnabled(isFullscreenEnabled)}
		>
			<div>
				<button onClick={() => setisFullscreenEnabled(true)}>Go Fullscreen</button>
                                 <div>I am having some content over here(This content is not scrollable under fullscreen mode)</div>
			</div>
		</Fullscreen>

**Comment by vasilevich** [comment]
I think you are trying to copy the behavior akin to the youtube full screen player, which allows you to scroll down to the comments section in full screen mode aswell.
As far as I know this component does not add scrolling out of the box, and in order for you to do that you simpley need to give it a scrollable element.
I think in order for you to achieve a scroll effect,
the div that you put inside react full screen should be scrollable
for example:
```
<Fullscreen
		enabled={isFullscreenEnabled}
		onChange={(isFullscreenEnabled) => setisFullscreenEnabled(isFullscreenEnabled)}
	>
		<div style={{overflowY: 'scroll',height:"100%"}}>
			<button onClick={() => setisFullscreenEnabled(true)}>Go Fullscreen</button>
                              {Array(1000).fill(0).map(e=> <div>I am having some content over here(This content is not scrollable under fullscreen mode)</div>)}
		</div>
	</Fullscreen>
```
Note I did not test this code so copy with attention. and if it doesnt work let me know or try this out:
https://stackoverflow.com/a/44526608

**Comment by vasilevich** [comment]
due to no response I am closing this issue,  feel free to reopen if you still need help

**Comment by MichalPP** [comment]
works for me, but I wonder why the style has to be on the <div> and not on <Fullscreen> element.
