### ISSUE TITLE
New npm package version neccessary

### ISSUE THREAD

**Issue by Hmve** [vasilevich/react-fullscreen-crossbrowser#9]
Hi vasilevich,
would it be possible to update the version of the react-fullscreen-crossbrowser and publish it to npm, so that the latest changes take place in the npm package as well! I would like to use the package with React 18.x.x.

Thank you!

**Comment by vasilevich** [comment]
Hi , I can publish it, but it has not been tested by me, can you confirm that it works by using the module from githib directly?
`yarn install https://github.com/vasilevich/react-fullscreen-crossbrowser`

Once you confirm I will publish it right away

**Comment by Hmve** [comment]
Hi,
I can confirm, that it works on Windows 10 with Chrome, Firefox, Edge and Opera. Other Systems are currently not available to me.
But there is still a warning by parsing the source map:
`WARNING in ./node_modules/react-fullscreen-crossbrowser/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\XXX\XXX\XXX\XXX\MYPROJECT\node_modules\react-fullscreen-crossbrowser\src\index.tsx' file: Error: ENOENT: no such file or directory, open 'C:\Users\XXX\XXX\XXX\XXX\MYPROJECT\node_modules\react-fullscreen-crossbrowser\src\index.tsx'`

This warning results from the missing 'index.tsx' which you adress in the index.js.map with 
`sources":["../src/index.tsx"]`. 

So, either you publish the index.tsx within the package or you set the sourceRoot in the index.js.map to the github repo. I would not recommend the latter, since you do not work with branches in your repo and each change on the repo would directly effect published versions

**Comment by vasilevich** [comment]
Hi, Thank you for helping me test this out, I have published the changes to npm, please confirm that it is ok with you, and please feel free to make any pull requests if you feel like anything is missing

**Comment by Hmve** [comment]
Thank you for publishing it. The version you publish has still the problem with the missing index.tsx. And it seems that you only updated the version to 1.1.1 localy because the change was not in your repo.
I added a pull request, which should fix both problems.
Would be great if you could publish it again with those fixes.

**Comment by vasilevich** [comment]
will do right now, thanks

and sorry

**Comment by Hmve** [comment]
Thank you, It does work!
